[project]
name = "odoo-addons-sygel-technology-sy-purchase-workflow"
version = "17.0.20250312.0"
dependencies = [
    "odoo-addon-purchase_create_related>=17.0dev,<17.1dev",
    "odoo-addon-purchase_order_no_price>=17.0dev,<17.1dev",
    "odoo-addon-purchase_product_warn_message>=17.0dev,<17.1dev",
    "odoo-addon-queued_purchase_notify>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
